### ISSUE TITLE
AdZHosts list is no more.

### ISSUE THREAD

**Issue by Atavic** [JoseGalRe/Hosty#2]
Hello, I'd like to let you know that:

> the AdZHosts project is officially closed after more than 10 years of service

[Source](https://adzhosts.eu/)

Last remnants are [here](https://sourceforge.net/projects/adzhosts/).

**Comment by Atavic** [comment]
There's only a link to a Telegram group on Sourceforge.

**Comment by JoseGalRe** [comment]
hi, oh it's a bad news, but i understand!, thanks for all on this time!
