### ISSUE TITLE
Invalid Domains

### ISSUE THREAD

**Issue by p1r473** [JoseGalRe/Hosty#4]
The following domains contain illegal characters and are illegal
Notice, the first one looks okay, but the PiHole script is picking up an illegal character in it.
I recommend deleting the domain, and retyping it with normal ASCII characters.

```
  [i] Target: https://raw.githubusercontent.com/JoseGalRe/Hosty/master/bits/hosty.blacklist
  [✓] Status: Retrieval successful
  [i] Received 537 domains, 2 domains invalid!
      Sample of invalid domains:
      - alert.com–securitynotice.us
      - univisión.click
```

**Comment by p1r473** [comment]
@JoseGalRe

**Comment by JoseGalRe** [comment]
https://github.com/JoseGalRe/Hosty/commit/2ddbf283a391130816251aa654818cf253302ca1
